"""Export the real 3-vs-8 samples used by the Pixel Nudge demo.

The source is sklearn.datasets.load_digits, which packages a copy of the UCI
Optical Recognition of Handwritten Digits data. This script intentionally
exports raw pixels only: browser-side TypeScript trains the demo classifier.
"""

from pathlib import Path

from sklearn.datasets import load_digits


OUTPUT = Path("src/app/adversarial-sketch/digits-data.ts")


def format_values(values: list[int], width: int = 20) -> str:
    rows = []
    for start in range(0, len(values), width):
        row = ", ".join(str(value) for value in values[start : start + width])
        rows.append(f"  {row},")
    return "\n".join(rows)


def main() -> None:
    digits = load_digits()
    selected_indices = [
        index
        for index, label in enumerate(digits.target)
        if int(label) in (3, 8)
    ]
    labels = [int(digits.target[index]) for index in selected_indices]
    pixels = [
        int(value)
        for index in selected_indices
        for value in digits.data[index]
    ]

    source = """// Generated by scripts/export_digits_3_vs_8.py. Do not hand-edit.
// Source: sklearn.datasets.load_digits, a copy of the UCI Optical Recognition
// of Handwritten Digits data. Each sample is a real 8x8 image with pixels 0..16.

export const DIGIT_SAMPLE_COUNT = %d;
export const DIGIT_PIXEL_WIDTH = 8;
export const DIGIT_RAW_LABELS = new Uint8Array([
%s
]);
export const DIGIT_RAW_PIXELS = new Uint8Array([
%s
]);
""" % (len(labels), format_values(labels), format_values(pixels))

    OUTPUT.write_text(source, encoding="utf-8")
    print(f"Wrote {OUTPUT} with {len(labels)} real digit images.")


if __name__ == "__main__":
    main()
