#!/usr/bin/env node

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  PROJECTS,
  getProjectPath,
  type ProjectCollection,
} from "../src/lib/projects.ts";

const ROOT = process.cwd();
const OUTPUT = resolve(ROOT, "PROJECTS.md");
const COLLECTIONS: Array<{ id: ProjectCollection; title: string }> = [
  { id: "demos", title: "Demos" },
  { id: "nerdy-stuff", title: "Nerdy Stuff" },
  { id: "bulletin", title: "Bulletin" },
];

function cell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

function render(): string {
  const lines = [
    "# Projects Registry",
    "",
    "<!-- Generated by scripts/projects-doc.ts from src/content/projects.json. -->",
    "",
    "This overview is generated from the same validated registry that renders the site.",
    "Edit `src/content/projects.json`, then run `npm run projects:docs`.",
    "",
  ];

  for (const collection of COLLECTIONS) {
    lines.push(
      `## ${collection.title}`,
      "",
      "| Project | Status | Path | Summary |",
      "|---|---|---|---|",
    );
    for (const project of PROJECTS.filter(
      (entry) => entry.collection === collection.id,
    ).sort((left, right) => left.order - right.order)) {
      lines.push(
        `| ${cell(project.title)} | \`${project.status}\` | \`${getProjectPath(project)}\` | ${cell(project.summary)} |`,
      );
    }
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

const expected = render();
if (process.argv.includes("--verify")) {
  const actual = readFileSync(OUTPUT, "utf8");
  if (actual !== expected) {
    throw new Error("PROJECTS.md is stale; run npm run projects:docs");
  }
  console.log(`Verified PROJECTS.md against ${PROJECTS.length} project records.`);
} else {
  writeFileSync(OUTPUT, expected);
  console.log(`Generated PROJECTS.md from ${PROJECTS.length} project records.`);
}
