import type { GeneratedData, Schema, ColumnType } from "../types";

function formatSQLValue(value: unknown, type: ColumnType): string {
  if (value === null || value === undefined) {
    return "NULL";
  }

  switch (type) {
    case "string":
    case "text":
    case "email":
    case "uuid":
    case "date":
      return `'${String(value).replace(/'/g, "''")}'`;
    case "integer":
      return String(Math.round(Number(value)));
    case "float":
      return String(Number(value));
    case "boolean":
      return value ? "TRUE" : "FALSE";
    default:
      return `'${String(value).replace(/'/g, "''")}'`;
  }
}

export function exportAsSQL(data: GeneratedData, schema: Schema): string {
  let sql = "-- Generated by Data Forge\n-- https://rusen.ai/demos/data-forge\n\n";

  for (const table of schema.tables) {
    const rows = data[table.name] || [];
    if (rows.length === 0) continue;

    const columns = table.columns.map((c) => c.name);

    sql += `-- Table: ${table.name}\n`;

    for (const row of rows) {
      const values = columns.map((colName) => {
        const col = table.columns.find((c) => c.name === colName)!;
        return formatSQLValue(row[colName], col.type);
      });

      sql += `INSERT INTO ${table.name} (${columns.join(", ")}) VALUES (${values.join(", ")});\n`;
    }

    sql += "\n";
  }

  return sql;
}

export function exportAsJSON(data: GeneratedData): string {
  return JSON.stringify(data, null, 2);
}

function escapeCSV(value: unknown): string {
  if (value === null || value === undefined) {
    return "";
  }
  const str = String(value);
  if (str.includes(",") || str.includes('"') || str.includes("\n")) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export function exportAsCSV(data: GeneratedData, tableName: string): string {
  const rows = data[tableName] || [];
  if (rows.length === 0) return "";

  const headers = Object.keys(rows[0]);
  const csvRows = [
    headers.join(","),
    ...rows.map((row) => headers.map((h) => escapeCSV(row[h])).join(",")),
  ];

  return csvRows.join("\n");
}

export function exportAllAsCSV(data: GeneratedData): string {
  let result = "";

  for (const tableName of Object.keys(data)) {
    result += `# Table: ${tableName}\n`;
    result += exportAsCSV(data, tableName);
    result += "\n\n";
  }

  return result;
}

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text);
}
